name: Validate

on:
  push:
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Validate
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Install jsonschema
        run: pip install jsonschema==4.6.1

      - name: Validate JSON files
        run: python schemas/validate.py
