name: Validate

on:
  push:
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install jsonschema
        run: pip install jsonschema==4.6.1

      - run: |
          python - <<'PY'
          import sys, urllib.request, pprint
          url = "https://github.com/graalvm/graal-languages-ea-builds/releases/graaljs-25.0.0-ea.19/graaljs-jvm-25.0.0-ea.19-macos-amd64.tar.gz"
          req = urllib.request.Request(url, method="HEAD")
          try:
              urllib.request.urlopen(req)
          except urllib.error.HTTPError as e:
              print("STATUS:", e.code, e.reason)
              print("URL    :", e.geturl())
              print("HEADERS:"); pprint.pprint(dict(e.headers))
          PY

      - name: Validate JSON files
        run: python schemas/validate.py